spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/makerhub_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG