spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/makerhub_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG

# prop custom pour l'implementation de JWT
app:
  security:
    jwt:
      access-expires-at: 900_000 # 15 min
      refresh-expires-at: 2_592_000_000 # 30 jours
      prefix: "Bearer "
      auth-header: "authorization"
      access-secret: s3cr3t
      refresh-secret: s4cr4t